DefaultContentLanguage = "en"
author = ""
baseURL = "https://gohugo.io/"
copyright = "Copyright © 2022, Marketing Blog"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
languageCode = "en"
paginate = 3
theme = "github.com/jonathanjanssens/hugo-casper3"
title = "Marketing Blog"
[[menu.main]]
identifier = "Posts"
name = "Posts"
url = ""
weight = nil
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10
[params]
description = "Demo MKT ID"
facebook = ""
github = ""
logo = "/images/hugo.png"
mainSections = ["post"]
twitter = ""
[privacy.instagram]
disabled = false
simple = true
[privacy.twitter]
disabled = false
enableDNT = true
simple = true
[privacy.vimeo]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
